services:
  - type: web
    name: leaflens
    runtime: python

    buildCommand: |
      chmod +x build.sh
      ./build.sh

    startCommand: gunicorn leaflens.wsgi:application

    envVars:
      - key: PYTHON_VERSION
        value: "3.10.11"

      - key: DEBUG
        value: "False"

      - key: SECRET_KEY
        generateValue: true